//! Output classes: the metadata `#[psclass]` generates, the method
//! table `#[psmethods]` adds, and the entry the module table is built
//! from.

use crate::{ErrorCategory, PsError, PsObject, PsResult};
use core::ffi::c_void;
use core::marker::PhantomData;

/// A Rust type with a CLR counterpart the shell can declare, so it
/// can stand as a parameter type or a class field type. Generated by
/// `#[psenum]`.
pub trait PsTyped {
    /// The CLR type name the shell declares for it.
    const CLR_NAME: &'static str;
    /// True when the CLR type is a value type (an enum or struct), so
    /// the shell boxes it without a null check.
    const VALUE_TYPE: bool;
}

/// Generated by `#[psclass]` and `#[psenum]`.
pub trait PsClassMeta: 'static {
    /// CLR type name (or `PSTypeName` for psobject mode).
    const NAME: &'static str;
    /// `copied`, `proxy`, `psobject`, or `enum`.
    const MODE: &'static str;

    /// JSON object describing the class and its fields, without an
    /// id. Built at run time because a field's CLR type name may come
    /// from another type's [`PsTyped`] impl.
    fn descriptor() -> String;

    /// The class id assigned by `export_module!`, resolved once.
    fn class_id() -> PsResult<u32>;

    /// Reads one field of a proxy instance.
    ///
    /// # Safety
    /// `instance` must be a live pointer produced by this class's
    /// `IntoPs` in proxy mode.
    unsafe fn proxy_get(instance: *mut c_void, field_id: u32) -> PsResult<PsObject>;

    /// Runs one `#[psmethods]` method of a proxy instance with its
    /// packed argument block; a method returning `()` yields `$null`.
    ///
    /// # Safety
    /// As for [`PsClassMeta::proxy_get`]; `args` points at the block
    /// the generated shell packed for that method.
    unsafe fn proxy_call(instance: *mut c_void, method_id: u32, args: *const c_void) -> PsResult<PsObject>;

    /// Frees a proxy instance; called exactly once per instance.
    ///
    /// # Safety
    /// As for [`PsClassMeta::proxy_get`]; never called twice.
    unsafe fn proxy_drop(instance: *mut c_void);

    /// The bytes of native memory a proxy instance keeps alive, as the
    /// function named by `#[psclass(proxy, native_bytes = ...)]` reports
    /// them; 0 for a class that names none.
    ///
    /// # Safety
    /// As for [`PsClassMeta::proxy_get`].
    unsafe fn proxy_bytes(_instance: *mut c_void) -> u64 {
        0
    }
}

/// What a `#[psmethods]` constructor hands back to the constructor the
/// shell generates for it.
///
/// A C# constructor cannot swap in another object, so each mode hands
/// back what its constructor can make itself from. A proxy class boxes
/// the value and answers the pointer, which the constructor adopts as
/// the value it holds. A copied class answers the object its own
/// `IntoPs` builds, whose fields the constructor copies into itself.
///
/// `MODE` is a constant, so the branch not taken is compiled out.
pub fn construct<T: PsClassMeta + crate::IntoPs>(value: T) -> PsResult<PsObject> {
    if T::MODE == "proxy" {
        let raw = Box::into_raw(Box::new(value)) as usize as i64;
        crate::IntoPs::into_ps(raw)
    } else {
        crate::IntoPs::into_ps(value)
    }
}

/// Registry entry; index in the module's table is the class id.
pub struct ClassEntry {
    pub name: &'static str,
    pub descriptor: fn() -> String,
    pub proxy_get: unsafe fn(*mut c_void, u32) -> PsResult<PsObject>,
    pub proxy_call: unsafe fn(*mut c_void, u32, *const c_void) -> PsResult<PsObject>,
    pub proxy_drop: unsafe fn(*mut c_void),
    pub proxy_bytes: unsafe fn(*mut c_void) -> u64,
}

/// Finds a class's `#[psmethods]` impl by method resolution: the
/// [`PsMethods`] impl `#[psmethods]` generates for
/// `MethodsCollector<T>` is reached at the receiver's own type, while
/// the [`NoPsMethods`] default needs one more reference, so it is
/// chosen only when no impl exists. `#[psclass]` calls both traits'
/// methods on `&MethodsCollector::<T>::new()`.
pub struct MethodsCollector<T>(PhantomData<T>);

impl<T> MethodsCollector<T> {
    pub const fn new() -> Self {
        MethodsCollector(PhantomData)
    }
}

impl<T> Default for MethodsCollector<T> {
    fn default() -> Self {
        MethodsCollector::new()
    }
}

/// Generated by `#[psmethods] impl T { ... }` for `MethodsCollector<T>`.
pub trait PsMethods<T> {
    /// JSON array of the method descriptors.
    fn methods_descriptor(&self) -> String;

    /// Runs method `method_id` on `instance` with its packed `args`.
    ///
    /// # Safety
    /// `instance` is a live proxy of `T` and `args` points at the
    /// block the generated shell packed for that method.
    unsafe fn proxy_call(&self, instance: *mut c_void, method_id: u32, args: *const c_void) -> PsResult<PsObject>;
}

/// The default for a class without `#[psmethods]`: no methods, and a
/// call is an error.
pub trait NoPsMethods<T> {
    fn methods_descriptor(&self) -> String {
        "[]".to_string()
    }

    /// # Safety
    /// Reads nothing; the arguments are ignored.
    unsafe fn proxy_call(&self, _instance: *mut c_void, method_id: u32, _args: *const c_void) -> PsResult<PsObject> {
        Err(PsError::new(
            ErrorCategory::InvalidOperation,
            "PwrsNoMethods",
            format!("{} declares no #[psmethods]; method {method_id} does not exist", core::any::type_name::<T>()),
        ))
    }
}

impl<T> NoPsMethods<T> for &MethodsCollector<T> {}
