//! The traits a cmdlet type implements, the one-allocation instance
//! the runtime hands the managed side, and the registry entry the
//! module export table is built from. `#[cmdlet]` generates
//! [`CmdletBind`] and [`CmdletMeta`]; the author writes [`Cmdlet`].

use crate::{ErrorCategory, Pipeline, PsError, PsResult};
use core::ffi::c_void;
use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use pwrs_sys::{PsHandle, PsPhase, PsPhaseMask, PS_PHASE_BEGIN, PS_PHASE_END, PS_PHASE_MASK_BEGIN, PS_PHASE_MASK_END, PS_PHASE_PROCESS};

/// Reads the generated parameter block into the struct. Generated by
/// `#[cmdlet]`.
pub trait CmdletBind {
    /// # Safety
    /// `params` points to this cmdlet's generated block, valid for
    /// the duration of the phase.
    unsafe fn bind(&mut self, params: *const c_void) -> PsResult<()>;
}

/// One cmdlet type. The instance lives from `BeginProcessing` to
/// `Dispose` of the managed cmdlet. `bind` runs before the first
/// phase and again before any phase whose block reports a parameter
/// reassigned since the last one (pipeline input rebinds per record).
///
/// The default `begin` and `end` mark the pipeline token; the runtime
/// reads the mark after the phase and, for a type whose phase turned
/// out to be the default, tells the managed side to stop calling that
/// phase for later instances. An implemented `begin` or `end` never
/// sets the mark, so it is always called.
pub trait Cmdlet: CmdletBind + CmdletMeta + Default + Send + 'static {
    fn begin(&mut self, ps: &Pipeline<'_>) -> PsResult<()> {
        ps.__pwrs_default_phase();
        Ok(())
    }

    fn process(&mut self, ps: &Pipeline<'_>) -> PsResult<()>;

    fn end(&mut self, ps: &Pipeline<'_>) -> PsResult<()> {
        ps.__pwrs_default_phase();
        Ok(())
    }
}

/// Metadata the export table and descriptor read. Generated by
/// `#[cmdlet]`.
pub trait CmdletMeta {
    /// `Verb-Noun`.
    const NAME: &'static str;
    /// JSON object describing the cmdlet and its parameters, without
    /// an `id`; the module descriptor adds the id. Built at run time
    /// because a parameter's CLR type name may come from another
    /// type's [`crate::class::PsTyped`] impl.
    fn descriptor() -> String;
    /// The phases this type needs a native call for, learned at run
    /// time. One static per type.
    fn phase_mask() -> &'static AtomicU32;
}

/// The type-independent head of every [`Instance`]. The managed side
/// holds a pointer to it; the runtime dispatches through the two
/// function pointers and touches the flags directly. Laid out first
/// in the instance, so the pointer converts both ways.
#[repr(C)]
pub struct InstanceHeader {
    /// Binds if the block is dirty and runs the phase body.
    pub run: unsafe fn(*mut InstanceHeader, PsPhase, PsHandle, *const c_void) -> PsResult<()>,
    /// Frees the whole instance.
    pub drop: unsafe fn(*mut InstanceHeader),
    /// Set by `StopProcessing` from another thread.
    pub stopping: AtomicBool,
    /// True once `bind` has run.
    pub bound: bool,
    /// The UTF-16 buffer the stream writes build their text in. It
    /// lives on the instance because a `thread_local!` in a cdylib is
    /// reached through an indirect call into the dynamic linker on
    /// every access, which costs more than the conversion it holds.
    /// The managed side reads nothing past `bound`, so this appends.
    pub scratch: core::cell::Cell<Vec<u16>>,
}

/// One live cmdlet with its runtime state: a single allocation per
/// managed cmdlet.
#[repr(C)]
pub struct Instance<T> {
    pub header: InstanceHeader,
    pub cmdlet: T,
}

impl<T: Cmdlet> Instance<T> {
    /// Allocates an instance around `T::default()` and returns the
    /// header pointer the managed side keeps. Freed by `header.drop`.
    pub fn leak_new() -> *mut InstanceHeader {
        let inst = Box::new(Instance {
            header: InstanceHeader {
                run: run_phase::<T>,
                drop: drop_instance::<T>,
                stopping: AtomicBool::new(false),
                bound: false,
                scratch: core::cell::Cell::new(Vec::new()),
            },
            cmdlet: T::default(),
        });
        Box::into_raw(inst) as *mut InstanceHeader
    }
}

/// Every generated parameter block starts with its dirty word.
#[inline]
unsafe fn dirty_word(params: *const c_void) -> u64 {
    if params.is_null() {
        0
    } else {
        core::ptr::read_unaligned(params as *const u64)
    }
}

unsafe fn run_phase<T: Cmdlet>(hdr: *mut InstanceHeader, phase: PsPhase, cmdlet: PsHandle, params: *const c_void) -> PsResult<()> {
    let inst = &mut *(hdr as *mut Instance<T>);
    let ps = Pipeline::new(cmdlet, &inst.header.stopping, &inst.header.scratch);
    let dirty = dirty_word(params);
    if !inst.header.bound || dirty != 0 {
        let t = crate::trace::start();
        inst.cmdlet.bind(params)?;
        inst.header.bound = true;
        crate::trace::on_bind(t);
    }
    let t = crate::trace::start();
    let result = match phase {
        PS_PHASE_BEGIN => inst.cmdlet.begin(&ps),
        PS_PHASE_PROCESS => inst.cmdlet.process(&ps),
        PS_PHASE_END => inst.cmdlet.end(&ps),
        other => Err(PsError::new(ErrorCategory::InvalidOperation, "PwrsBadPhase", format!("unknown phase {other}")).terminating()),
    };
    crate::trace::on_body(t);
    if ps.took_default_phase() {
        let empty: PsPhaseMask = match phase {
            PS_PHASE_BEGIN => PS_PHASE_MASK_BEGIN,
            PS_PHASE_END => PS_PHASE_MASK_END,
            _process => 0,
        };
        if empty != 0 {
            T::phase_mask().fetch_and(!empty, Ordering::Relaxed);
            crate::trace::on_phase_learned();
        }
    }
    if crate::surface::enabled() {
        crate::surface::record(<T as CmdletMeta>::NAME, phase, dirty, ps.asked());
    }
    result
}

unsafe fn drop_instance<T: Cmdlet>(hdr: *mut InstanceHeader) {
    drop(Box::from_raw(hdr as *mut Instance<T>));
}

impl InstanceHeader {
    /// Sets the stop flag; any thread.
    #[inline]
    pub fn stop(&self) {
        self.stopping.store(true, Ordering::Relaxed);
    }
}

/// Registry entry; index in the module's table is the cmdlet id.
pub struct CmdletEntry {
    pub name: &'static str,
    pub descriptor: fn() -> String,
    pub new: fn() -> *mut InstanceHeader,
    /// The type's learned phase mask.
    pub phase_mask: fn() -> &'static AtomicU32,
}
