//! Argument completers and dynamic parameters.
//!
//! A completer runs on the completion thread with no pipeline, so it
//! receives only the word being completed and the surrounding command
//! text. Dynamic parameters are computed before binding from the
//! statically bound parameters.

use crate::convert::PsArray;
use crate::{IntoPs, PsObject, PsResult};

/// What the user has typed so far at a completion point.
pub struct CompletionContext {
    /// The partial word under the cursor.
    pub word: String,
    /// The full command line text.
    pub command: String,
    /// Parameters already bound, by name, as untyped objects.
    pub bound: crate::PsHashtable,
}

/// The kind of a completion result, matching
/// `System.Management.Automation.CompletionResultType`.
#[derive(Clone, Copy)]
pub enum CompletionKind {
    Text,
    History,
    Command,
    ProviderItem,
    ProviderContainer,
    Property,
    Method,
    ParameterName,
    ParameterValue,
    Variable,
    Namespace,
    Type,
    Keyword,
    DynamicKeyword,
}

impl CompletionKind {
    fn name(self) -> &'static str {
        match self {
            CompletionKind::Text => "Text",
            CompletionKind::History => "History",
            CompletionKind::Command => "Command",
            CompletionKind::ProviderItem => "ProviderItem",
            CompletionKind::ProviderContainer => "ProviderContainer",
            CompletionKind::Property => "Property",
            CompletionKind::Method => "Method",
            CompletionKind::ParameterName => "ParameterName",
            CompletionKind::ParameterValue => "ParameterValue",
            CompletionKind::Variable => "Variable",
            CompletionKind::Namespace => "Namespace",
            CompletionKind::Type => "Type",
            CompletionKind::Keyword => "Keyword",
            CompletionKind::DynamicKeyword => "DynamicKeyword",
        }
    }
}

/// One completion offered to the user.
pub struct Completion {
    pub text: String,
    pub list_item: String,
    pub kind: CompletionKind,
    pub tooltip: String,
}

impl Completion {
    /// A value completion whose list item and tooltip are the text.
    pub fn value(text: impl Into<String>) -> Completion {
        let text = text.into();
        Completion { list_item: text.clone(), tooltip: text.clone(), kind: CompletionKind::ParameterValue, text }
    }

    pub fn with_tooltip(mut self, tooltip: impl Into<String>) -> Completion {
        self.tooltip = tooltip.into();
        self
    }

    /// The `string[4]` the vtable expects: text, list item, kind, tooltip.
    pub(crate) fn to_object(&self) -> PsResult<PsObject> {
        PsArray(vec![self.text.clone(), self.list_item.clone(), self.kind.name().to_string(), self.tooltip.clone()]).into_ps()
    }
}

/// Generated by `#[completer]`.
pub trait CompleterFn: 'static {
    /// `Cmdlet-Name/Parameter`, the key the shell attaches the
    /// completer to.
    const TARGET: &'static str;
    fn complete(ctx: &CompletionContext) -> PsResult<Vec<Completion>>;
}

/// Registry entry; index is the completer id.
pub struct CompleterEntry {
    pub target: &'static str,
    pub run: fn(&CompletionContext) -> PsResult<Vec<Completion>>,
}

/// A dynamic parameter a cmdlet adds at bind time.
pub struct DynamicParam {
    pub name: String,
    /// CLR type name, e.g. `System.String` or `System.Int32`.
    pub clr_type: String,
    pub mandatory: bool,
    /// `-1` for a named parameter.
    pub position: i64,
    pub set: Option<String>,
    pub help: String,
    pub validate_set: Vec<String>,
}

impl DynamicParam {
    pub fn string(name: impl Into<String>) -> DynamicParam {
        DynamicParam {
            name: name.into(),
            clr_type: "System.String".to_string(),
            mandatory: false,
            position: -1,
            set: None,
            help: String::new(),
            validate_set: Vec::new(),
        }
    }

    pub fn mandatory(mut self) -> DynamicParam {
        self.mandatory = true;
        self
    }

    pub fn with_validate_set(mut self, values: impl IntoIterator<Item = String>) -> DynamicParam {
        self.validate_set = values.into_iter().collect();
        self
    }

    /// The parameter as one line of the packed answer: seven cells
    /// joined by U+0001 (name, CLR type name, mandatory as `1` or `0`,
    /// position, parameter set name, help, validate-set values joined by
    /// U+0002), so an answer crosses as one managed string however many
    /// parameters it carries.
    pub(crate) fn packed(&self) -> String {
        format!(
            "{}\u{1}{}\u{1}{}\u{1}{}\u{1}{}\u{1}{}\u{1}{}",
            self.name,
            self.clr_type,
            if self.mandatory { "1" } else { "0" },
            self.position,
            self.set.as_deref().unwrap_or(""),
            self.help,
            self.validate_set.join("\u{2}")
        )
    }
}

/// The packed answer the vtable expects: every parameter's line joined
/// by U+0003, and `$null` for none.
pub(crate) fn pack_dynamic_params(params: &[DynamicParam]) -> PsResult<PsObject> {
    if params.is_empty() {
        return PsObject::null().into_ps();
    }
    let lines: Vec<String> = params.iter().map(DynamicParam::packed).collect();
    lines.join("\u{3}").into_ps()
}

/// Generated by `#[dynamic_params]` on a cmdlet.
pub trait DynamicParams {
    fn dynamic_parameters(bound: &crate::PsHashtable) -> PsResult<Vec<DynamicParam>>;
}
