//! A function that runs when the module is imported and one that runs
//! when it is removed.
//!
//! The generated shell implements `IModuleAssemblyInitializer` and
//! `IModuleAssemblyCleanup` for the hooks the module declares and no
//! others, so a module without either is not called at import or
//! removal. A hook runs on the thread executing `Import-Module` or
//! `Remove-Module`, with no cmdlet and no pipeline.
//!
//! A removal unloads nothing: the native library stays mapped and its
//! statics keep their values. So `on_import` runs again on every
//! import, including one that follows a removal in the same session,
//! and `on_remove` is the module's only chance to release what an
//! import took, since no destructor will. An `Err` from `on_import`
//! fails the import; an `Err` from `on_remove` is reported by
//! `Remove-Module` and the removal goes ahead.

use crate::PsResult;

/// Generated by `#[on_import]`.
pub trait OnImport: 'static {
    fn run() -> PsResult<()>;
}

/// Generated by `#[on_remove]`.
pub trait OnRemove: 'static {
    fn run() -> PsResult<()>;
}

/// The hooks a module registered through `export_module!`.
pub struct Lifecycle {
    pub on_import: Option<fn() -> PsResult<()>>,
    pub on_remove: Option<fn() -> PsResult<()>>,
}

/// The op `pwrs_module_lifecycle` takes for the import hook.
pub const OP_IMPORT: u32 = 0;
/// The op `pwrs_module_lifecycle` takes for the removal hook.
pub const OP_REMOVE: u32 = 1;
